### ISSUE TITLE
Building linux deskop app with the plugin fails the build

### ISSUE THREAD

**Issue by tomaszpolanski** [rive-app/window-utils#3]
When trying to build the project when the plugin is in `pubspec.yaml`, the build fails as for now it's not supported:
```
[ +171 ms] flutter/generated_plugin_registrant.cc:7:10: fatal error: 'window_utils.h' file not found
[        ] #include <window_utils.h>
[        ]          ^~~~~~~~~~~~~~~~
[  +20 ms] 1 error generated.
[   +3 ms] Makefile:141: recipe for target '/home/kriger/Documents/GitHub/window-utils/example/linux/../build/linux/obj/debug/flutter/generated_plugin_registrant.o' failed
```

Until the Linux is supported, the plugin should disable support for it.

**Comment by stuartmorgan** [comment]
Did you make the necessary manual changes to manually integrate the plugin into your makefile (it's the same as for an FDE Linux plugin if you've used any of those)? Since the header does exist in the repo, the most likely reason for this error would be makefile issues.

The fact that it doesn't handle all the method channel message couldn't cause this error.

**Comment by rodydavis** [comment]
Yeah I'm working on the linux side at the moment. But having issues as the GLFW context is not provided from the FlutterWindow context. I see that it is calling into the flutter engine itself to call glfw. 

The issue with using GNOME or X11 is that not all linux distros use the same window library. 

https://www.glfw.org/docs/3.0/window.html

```
// Returns the screen object that contains monitors.
GdkScreen *GetScreen() {
  GdkDisplay *display = gdk_display_get_default();
  if (!display) {
    return nullptr;
  }
  GdkScreen *screen = gdk_display_get_default_screen(display);
  return screen;
}
```

Here it is using gdk which is a subset.

Is there a way to get the proper context to glfw?

```
 private:
  // Handle for interacting with the C API's window.
  //
  // Note: window_ is conceptually owned by the controller, not this object.
  FlutterDesktopWindowRef window_;
```

that I believe is the ref needed to call updates with glfw

**Comment by stuartmorgan** [comment]
> Yeah I'm working on the linux side at the moment.

My point though is that the error above looks like an application-level configuration error in including the plugin (which is currently a pain on Linux, so that wouldn't be surprising) rather than something related to whether the plugin is ready as suggested by the PR above.

**Comment by stuartmorgan** [comment]
@rodydavis Feel free to file feature requests for the GLFW embedding API in the Flutter repository and mention me, or email the FDE mailing list with general questions about using it.

**Comment by rodydavis** [comment]
@stuartmorgan will do thank you!

**Comment by tomaszpolanski** [comment]
@rodydavis How about closing this ticket as the issue with building on Linux is resolved - the application with the plugin builds but of course calling the plugin won't, but that will be solved when you will add Linux support
